### ISSUE TITLE
client(or application)_id in config

### ISSUE THREAD

**Issue by NamelessGO** [STadas/Ankicord#4]
i didn't understand how to make a pull request 😆 
Thanks for the config addon, makes the integration more fun and the icon is awesome
gl to your uni

In the future
you could try creating the option to change the icon using the same idea as the background addon -that use a photo folder to change the background

ty for the addon

**Comment by STadas** [comment]
Hi, by icon do you mean this?:
![image](https://user-images.githubusercontent.com/43136162/113509208-0008b580-955d-11eb-9b5e-1779e8945de7.png)

If so, unfortunately you can't change that or the "Anki" title part from the code/config. So if you do want to change them you'll have to make your own Discord application with the desired title through the developer portal, add the files there and change the client_id variable to your own (application id in the portal) in the addon code.

If you do still want to do that, it's not a very difficult process. The only real requirement is that you name the uploaded icon file "anki", otherwise it won't work. Here's the developer portal link: https://discord.com/developers

Sorry if that doesn't help, but do let me know if there's anything else!
(Also, you gave me an idea just now to add a config option for client_id in the config, I'll add that to the list of TODO's which I'll get around to eventually, so thank you)
